// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randexample.proto

#ifndef PROTOBUF_randexample_2eproto__INCLUDED
#define PROTOBUF_randexample_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace randexample {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_randexample_2eproto();
void protobuf_AssignDesc_randexample_2eproto();
void protobuf_ShutdownFile_randexample_2eproto();

class Request;
class Reply;

// ===================================================================

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();
  
  Request(const Request& from);
  
  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();
  
  void Swap(Request* other);
  
  // implements Message ----------------------------------------------
  
  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 nMessage = 1;
  inline bool has_nmessage() const;
  inline void clear_nmessage();
  static const int kNMessageFieldNumber = 1;
  inline ::google::protobuf::int32 nmessage() const;
  inline void set_nmessage(::google::protobuf::int32 value);
  
  // optional int32 nSample = 2;
  inline bool has_nsample() const;
  inline void clear_nsample();
  static const int kNSampleFieldNumber = 2;
  inline ::google::protobuf::int32 nsample() const;
  inline void set_nsample(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:randexample.Request)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 nmessage_;
  ::google::protobuf::int32 nsample_;
  friend void  protobuf_AddDesc_randexample_2eproto();
  friend void protobuf_AssignDesc_randexample_2eproto();
  friend void protobuf_ShutdownFile_randexample_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Reply : public ::google::protobuf::Message {
 public:
  Reply();
  virtual ~Reply();
  
  Reply(const Reply& from);
  
  inline Reply& operator=(const Reply& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Reply& default_instance();
  
  void Swap(Reply* other);
  
  // implements Message ----------------------------------------------
  
  Reply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Reply& from);
  void MergeFrom(const Reply& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated double r = 1;
  inline int r_size() const;
  inline void clear_r();
  static const int kRFieldNumber = 1;
  inline double r(int index) const;
  inline void set_r(int index, double value);
  inline void add_r(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      r() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_r();
  
  // @@protoc_insertion_point(class_scope:randexample.Reply)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedField< double > r_;
  friend void  protobuf_AddDesc_randexample_2eproto();
  friend void protobuf_AssignDesc_randexample_2eproto();
  friend void protobuf_ShutdownFile_randexample_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Reply* default_instance_;
};
// ===================================================================


// ===================================================================

// Request

// optional int32 nMessage = 1;
inline bool Request::has_nmessage() const {
  return _has_bit(0);
}
inline void Request::clear_nmessage() {
  nmessage_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Request::nmessage() const {
  return nmessage_;
}
inline void Request::set_nmessage(::google::protobuf::int32 value) {
  _set_bit(0);
  nmessage_ = value;
}

// optional int32 nSample = 2;
inline bool Request::has_nsample() const {
  return _has_bit(1);
}
inline void Request::clear_nsample() {
  nsample_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 Request::nsample() const {
  return nsample_;
}
inline void Request::set_nsample(::google::protobuf::int32 value) {
  _set_bit(1);
  nsample_ = value;
}

// -------------------------------------------------------------------

// Reply

// repeated double r = 1;
inline int Reply::r_size() const {
  return r_.size();
}
inline void Reply::clear_r() {
  r_.Clear();
}
inline double Reply::r(int index) const {
  return r_.Get(index);
}
inline void Reply::set_r(int index, double value) {
  r_.Set(index, value);
}
inline void Reply::add_r(double value) {
  r_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
Reply::r() const {
  return r_;
}
inline ::google::protobuf::RepeatedField< double >*
Reply::mutable_r() {
  return &r_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace randexample

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_randexample_2eproto__INCLUDED
