// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uRPC.proto

#ifndef PROTOBUF_uRPC_2eproto__INCLUDED
#define PROTOBUF_uRPC_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "Log.pb.h"
// @@protoc_insertion_point(includes)

namespace urpc {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_uRPC_2eproto();
void protobuf_AssignDesc_uRPC_2eproto();
void protobuf_ShutdownFile_uRPC_2eproto();

class Request;
class Response;
class Server;
class Server_Record;

enum Server_Record_Protocol {
  Server_Record_Protocol_TCP = 1,
  Server_Record_Protocol_UDP = 2
};
bool Server_Record_Protocol_IsValid(int value);
const Server_Record_Protocol Server_Record_Protocol_Protocol_MIN = Server_Record_Protocol_TCP;
const Server_Record_Protocol Server_Record_Protocol_Protocol_MAX = Server_Record_Protocol_UDP;
const int Server_Record_Protocol_Protocol_ARRAYSIZE = Server_Record_Protocol_Protocol_MAX + 1;

const ::google::protobuf::EnumDescriptor* Server_Record_Protocol_descriptor();
inline const ::std::string& Server_Record_Protocol_Name(Server_Record_Protocol value) {
  return ::google::protobuf::internal::NameOfEnum(
    Server_Record_Protocol_descriptor(), value);
}
inline bool Server_Record_Protocol_Parse(
    const ::std::string& name, Server_Record_Protocol* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Server_Record_Protocol>(
    Server_Record_Protocol_descriptor(), name, value);
}
// ===================================================================

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();
  
  Request(const Request& from);
  
  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();
  
  void Swap(Request* other);
  
  // implements Message ----------------------------------------------
  
  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string service = 1;
  inline bool has_service() const;
  inline void clear_service();
  static const int kServiceFieldNumber = 1;
  inline const ::std::string& service() const;
  inline void set_service(const ::std::string& value);
  inline void set_service(const char* value);
  inline void set_service(const char* value, size_t size);
  inline ::std::string* mutable_service();
  
  // optional int32 version = 2;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 2;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);
  
  // optional bytes message = 3;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 3;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const void* value, size_t size);
  inline ::std::string* mutable_message();
  
  // @@protoc_insertion_point(class_scope:urpc.pb.Request)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* service_;
  static const ::std::string _default_service_;
  ::google::protobuf::int32 version_;
  ::std::string* message_;
  static const ::std::string _default_message_;
  friend void  protobuf_AddDesc_uRPC_2eproto();
  friend void protobuf_AssignDesc_uRPC_2eproto();
  friend void protobuf_ShutdownFile_uRPC_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message {
 public:
  Response();
  virtual ~Response();
  
  Response(const Response& from);
  
  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();
  
  void Swap(Response* other);
  
  // implements Message ----------------------------------------------
  
  Response* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool error = 1;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 1;
  inline bool error() const;
  inline void set_error(bool value);
  
  // optional bytes message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const void* value, size_t size);
  inline ::std::string* mutable_message();
  
  // repeated .urpc.pb.Log log = 3;
  inline int log_size() const;
  inline void clear_log();
  static const int kLogFieldNumber = 3;
  inline const ::urpc::pb::Log& log(int index) const;
  inline ::urpc::pb::Log* mutable_log(int index);
  inline ::urpc::pb::Log* add_log();
  inline const ::google::protobuf::RepeatedPtrField< ::urpc::pb::Log >&
      log() const;
  inline ::google::protobuf::RepeatedPtrField< ::urpc::pb::Log >*
      mutable_log();
  
  // @@protoc_insertion_point(class_scope:urpc.pb.Response)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  bool error_;
  ::std::string* message_;
  static const ::std::string _default_message_;
  ::google::protobuf::RepeatedPtrField< ::urpc::pb::Log > log_;
  friend void  protobuf_AddDesc_uRPC_2eproto();
  friend void protobuf_AssignDesc_uRPC_2eproto();
  friend void protobuf_ShutdownFile_uRPC_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// -------------------------------------------------------------------

class Server_Record : public ::google::protobuf::Message {
 public:
  Server_Record();
  virtual ~Server_Record();
  
  Server_Record(const Server_Record& from);
  
  inline Server_Record& operator=(const Server_Record& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Server_Record& default_instance();
  
  void Swap(Server_Record* other);
  
  // implements Message ----------------------------------------------
  
  Server_Record* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Server_Record& from);
  void MergeFrom(const Server_Record& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Server_Record_Protocol Protocol;
  static const Protocol TCP = Server_Record_Protocol_TCP;
  static const Protocol UDP = Server_Record_Protocol_UDP;
  static inline bool Protocol_IsValid(int value) {
    return Server_Record_Protocol_IsValid(value);
  }
  static const Protocol Protocol_MIN =
    Server_Record_Protocol_Protocol_MIN;
  static const Protocol Protocol_MAX =
    Server_Record_Protocol_Protocol_MAX;
  static const int Protocol_ARRAYSIZE =
    Server_Record_Protocol_Protocol_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Protocol_descriptor() {
    return Server_Record_Protocol_descriptor();
  }
  static inline const ::std::string& Protocol_Name(Protocol value) {
    return Server_Record_Protocol_Name(value);
  }
  static inline bool Protocol_Parse(const ::std::string& name,
      Protocol* value) {
    return Server_Record_Protocol_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // optional string service = 1;
  inline bool has_service() const;
  inline void clear_service();
  static const int kServiceFieldNumber = 1;
  inline const ::std::string& service() const;
  inline void set_service(const ::std::string& value);
  inline void set_service(const char* value);
  inline void set_service(const char* value, size_t size);
  inline ::std::string* mutable_service();
  
  // optional .urpc.pb.Server.Record.Protocol protocol = 2;
  inline bool has_protocol() const;
  inline void clear_protocol();
  static const int kProtocolFieldNumber = 2;
  inline ::urpc::pb::Server_Record_Protocol protocol() const;
  inline void set_protocol(::urpc::pb::Server_Record_Protocol value);
  
  // optional string name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  
  // optional int32 ttl = 4;
  inline bool has_ttl() const;
  inline void clear_ttl();
  static const int kTtlFieldNumber = 4;
  inline ::google::protobuf::int32 ttl() const;
  inline void set_ttl(::google::protobuf::int32 value);
  
  // optional int32 priority = 5;
  inline bool has_priority() const;
  inline void clear_priority();
  static const int kPriorityFieldNumber = 5;
  inline ::google::protobuf::int32 priority() const;
  inline void set_priority(::google::protobuf::int32 value);
  
  // optional int32 weight = 6;
  inline bool has_weight() const;
  inline void clear_weight();
  static const int kWeightFieldNumber = 6;
  inline ::google::protobuf::int32 weight() const;
  inline void set_weight(::google::protobuf::int32 value);
  
  // optional int32 port = 7;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 7;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);
  
  // optional string target = 8;
  inline bool has_target() const;
  inline void clear_target();
  static const int kTargetFieldNumber = 8;
  inline const ::std::string& target() const;
  inline void set_target(const ::std::string& value);
  inline void set_target(const char* value);
  inline void set_target(const char* value, size_t size);
  inline ::std::string* mutable_target();
  
  // @@protoc_insertion_point(class_scope:urpc.pb.Server.Record)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* service_;
  static const ::std::string _default_service_;
  int protocol_;
  ::std::string* name_;
  static const ::std::string _default_name_;
  ::google::protobuf::int32 ttl_;
  ::google::protobuf::int32 priority_;
  ::google::protobuf::int32 weight_;
  ::google::protobuf::int32 port_;
  ::std::string* target_;
  static const ::std::string _default_target_;
  friend void  protobuf_AddDesc_uRPC_2eproto();
  friend void protobuf_AssignDesc_uRPC_2eproto();
  friend void protobuf_ShutdownFile_uRPC_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Server_Record* default_instance_;
};
// -------------------------------------------------------------------

class Server : public ::google::protobuf::Message {
 public:
  Server();
  virtual ~Server();
  
  Server(const Server& from);
  
  inline Server& operator=(const Server& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Server& default_instance();
  
  void Swap(Server* other);
  
  // implements Message ----------------------------------------------
  
  Server* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Server& from);
  void MergeFrom(const Server& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Server_Record Record;
  
  // accessors -------------------------------------------------------
  
  // repeated .urpc.pb.Server.Record record = 1;
  inline int record_size() const;
  inline void clear_record();
  static const int kRecordFieldNumber = 1;
  inline const ::urpc::pb::Server_Record& record(int index) const;
  inline ::urpc::pb::Server_Record* mutable_record(int index);
  inline ::urpc::pb::Server_Record* add_record();
  inline const ::google::protobuf::RepeatedPtrField< ::urpc::pb::Server_Record >&
      record() const;
  inline ::google::protobuf::RepeatedPtrField< ::urpc::pb::Server_Record >*
      mutable_record();
  
  // @@protoc_insertion_point(class_scope:urpc.pb.Server)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::urpc::pb::Server_Record > record_;
  friend void  protobuf_AddDesc_uRPC_2eproto();
  friend void protobuf_AssignDesc_uRPC_2eproto();
  friend void protobuf_ShutdownFile_uRPC_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Server* default_instance_;
};
// ===================================================================


// ===================================================================

// Request

// optional string service = 1;
inline bool Request::has_service() const {
  return _has_bit(0);
}
inline void Request::clear_service() {
  if (service_ != &_default_service_) {
    service_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& Request::service() const {
  return *service_;
}
inline void Request::set_service(const ::std::string& value) {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void Request::set_service(const char* value) {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void Request::set_service(const char* value, size_t size) {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Request::mutable_service() {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  return service_;
}

// optional int32 version = 2;
inline bool Request::has_version() const {
  return _has_bit(1);
}
inline void Request::clear_version() {
  version_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 Request::version() const {
  return version_;
}
inline void Request::set_version(::google::protobuf::int32 value) {
  _set_bit(1);
  version_ = value;
}

// optional bytes message = 3;
inline bool Request::has_message() const {
  return _has_bit(2);
}
inline void Request::clear_message() {
  if (message_ != &_default_message_) {
    message_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& Request::message() const {
  return *message_;
}
inline void Request::set_message(const ::std::string& value) {
  _set_bit(2);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void Request::set_message(const char* value) {
  _set_bit(2);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void Request::set_message(const void* value, size_t size) {
  _set_bit(2);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Request::mutable_message() {
  _set_bit(2);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  return message_;
}

// -------------------------------------------------------------------

// Response

// optional bool error = 1;
inline bool Response::has_error() const {
  return _has_bit(0);
}
inline void Response::clear_error() {
  error_ = false;
  _clear_bit(0);
}
inline bool Response::error() const {
  return error_;
}
inline void Response::set_error(bool value) {
  _set_bit(0);
  error_ = value;
}

// optional bytes message = 2;
inline bool Response::has_message() const {
  return _has_bit(1);
}
inline void Response::clear_message() {
  if (message_ != &_default_message_) {
    message_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Response::message() const {
  return *message_;
}
inline void Response::set_message(const ::std::string& value) {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void Response::set_message(const char* value) {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void Response::set_message(const void* value, size_t size) {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Response::mutable_message() {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  return message_;
}

// repeated .urpc.pb.Log log = 3;
inline int Response::log_size() const {
  return log_.size();
}
inline void Response::clear_log() {
  log_.Clear();
}
inline const ::urpc::pb::Log& Response::log(int index) const {
  return log_.Get(index);
}
inline ::urpc::pb::Log* Response::mutable_log(int index) {
  return log_.Mutable(index);
}
inline ::urpc::pb::Log* Response::add_log() {
  return log_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::urpc::pb::Log >&
Response::log() const {
  return log_;
}
inline ::google::protobuf::RepeatedPtrField< ::urpc::pb::Log >*
Response::mutable_log() {
  return &log_;
}

// -------------------------------------------------------------------

// Server_Record

// optional string service = 1;
inline bool Server_Record::has_service() const {
  return _has_bit(0);
}
inline void Server_Record::clear_service() {
  if (service_ != &_default_service_) {
    service_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& Server_Record::service() const {
  return *service_;
}
inline void Server_Record::set_service(const ::std::string& value) {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void Server_Record::set_service(const char* value) {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void Server_Record::set_service(const char* value, size_t size) {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  service_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Server_Record::mutable_service() {
  _set_bit(0);
  if (service_ == &_default_service_) {
    service_ = new ::std::string;
  }
  return service_;
}

// optional .urpc.pb.Server.Record.Protocol protocol = 2;
inline bool Server_Record::has_protocol() const {
  return _has_bit(1);
}
inline void Server_Record::clear_protocol() {
  protocol_ = 1;
  _clear_bit(1);
}
inline ::urpc::pb::Server_Record_Protocol Server_Record::protocol() const {
  return static_cast< ::urpc::pb::Server_Record_Protocol >(protocol_);
}
inline void Server_Record::set_protocol(::urpc::pb::Server_Record_Protocol value) {
  GOOGLE_DCHECK(::urpc::pb::Server_Record_Protocol_IsValid(value));
  _set_bit(1);
  protocol_ = value;
}

// optional string name = 3;
inline bool Server_Record::has_name() const {
  return _has_bit(2);
}
inline void Server_Record::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& Server_Record::name() const {
  return *name_;
}
inline void Server_Record::set_name(const ::std::string& value) {
  _set_bit(2);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Server_Record::set_name(const char* value) {
  _set_bit(2);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Server_Record::set_name(const char* value, size_t size) {
  _set_bit(2);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Server_Record::mutable_name() {
  _set_bit(2);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  return name_;
}

// optional int32 ttl = 4;
inline bool Server_Record::has_ttl() const {
  return _has_bit(3);
}
inline void Server_Record::clear_ttl() {
  ttl_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 Server_Record::ttl() const {
  return ttl_;
}
inline void Server_Record::set_ttl(::google::protobuf::int32 value) {
  _set_bit(3);
  ttl_ = value;
}

// optional int32 priority = 5;
inline bool Server_Record::has_priority() const {
  return _has_bit(4);
}
inline void Server_Record::clear_priority() {
  priority_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 Server_Record::priority() const {
  return priority_;
}
inline void Server_Record::set_priority(::google::protobuf::int32 value) {
  _set_bit(4);
  priority_ = value;
}

// optional int32 weight = 6;
inline bool Server_Record::has_weight() const {
  return _has_bit(5);
}
inline void Server_Record::clear_weight() {
  weight_ = 0;
  _clear_bit(5);
}
inline ::google::protobuf::int32 Server_Record::weight() const {
  return weight_;
}
inline void Server_Record::set_weight(::google::protobuf::int32 value) {
  _set_bit(5);
  weight_ = value;
}

// optional int32 port = 7;
inline bool Server_Record::has_port() const {
  return _has_bit(6);
}
inline void Server_Record::clear_port() {
  port_ = 0;
  _clear_bit(6);
}
inline ::google::protobuf::int32 Server_Record::port() const {
  return port_;
}
inline void Server_Record::set_port(::google::protobuf::int32 value) {
  _set_bit(6);
  port_ = value;
}

// optional string target = 8;
inline bool Server_Record::has_target() const {
  return _has_bit(7);
}
inline void Server_Record::clear_target() {
  if (target_ != &_default_target_) {
    target_->clear();
  }
  _clear_bit(7);
}
inline const ::std::string& Server_Record::target() const {
  return *target_;
}
inline void Server_Record::set_target(const ::std::string& value) {
  _set_bit(7);
  if (target_ == &_default_target_) {
    target_ = new ::std::string;
  }
  target_->assign(value);
}
inline void Server_Record::set_target(const char* value) {
  _set_bit(7);
  if (target_ == &_default_target_) {
    target_ = new ::std::string;
  }
  target_->assign(value);
}
inline void Server_Record::set_target(const char* value, size_t size) {
  _set_bit(7);
  if (target_ == &_default_target_) {
    target_ = new ::std::string;
  }
  target_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Server_Record::mutable_target() {
  _set_bit(7);
  if (target_ == &_default_target_) {
    target_ = new ::std::string;
  }
  return target_;
}

// -------------------------------------------------------------------

// Server

// repeated .urpc.pb.Server.Record record = 1;
inline int Server::record_size() const {
  return record_.size();
}
inline void Server::clear_record() {
  record_.Clear();
}
inline const ::urpc::pb::Server_Record& Server::record(int index) const {
  return record_.Get(index);
}
inline ::urpc::pb::Server_Record* Server::mutable_record(int index) {
  return record_.Mutable(index);
}
inline ::urpc::pb::Server_Record* Server::add_record() {
  return record_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::urpc::pb::Server_Record >&
Server::record() const {
  return record_;
}
inline ::google::protobuf::RepeatedPtrField< ::urpc::pb::Server_Record >*
Server::mutable_record() {
  return &record_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace urpc

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::urpc::pb::Server_Record_Protocol>() {
  return ::urpc::pb::Server_Record_Protocol_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_uRPC_2eproto__INCLUDED
