# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='uRPC.proto',
  package='urpc.pb',
  serialized_pb='\n\nuRPC.proto\x12\x07urpc.pb\x1a\tLog.proto\"<\n\x07Request\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\x0c\"E\n\x08Response\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x19\n\x03log\x18\x03 \x03(\x0b\x32\x0c.urpc.pb.Log\"\x1c\n\tSubscribe\x12\x0f\n\x07version\x18\x01 \x01(\x05\"p\n\nServerList\x12*\n\x06server\x18\x01 \x03(\x0b\x32\x1a.urpc.pb.ServerList.Server\x1a\x36\n\x06Server\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08priority\x18\x03 \x01(\x05\"\x9c\x01\n\x0eKeyValueSeries\x12\x32\n\x08keyValue\x18\x01 \x03(\x0b\x32 .urpc.pb.KeyValueSeries.KeyValue\x1aV\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\".\n\tvalueType\x12\n\n\x06STRING\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\x12\t\n\x05INT32\x10\x03')



_KEYVALUESERIES_KEYVALUE_VALUETYPE = descriptor.EnumDescriptor(
  name='valueType',
  full_name='urpc.pb.KeyValueSeries.KeyValue.valueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DOUBLE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INT32', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=422,
  serialized_end=468,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='urpc.pb.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='service', full_name='urpc.pb.Request.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='urpc.pb.Request.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='urpc.pb.Request.message', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=94,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='urpc.pb.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='urpc.pb.Response.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='urpc.pb.Response.message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='log', full_name='urpc.pb.Response.log', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=165,
)


_SUBSCRIBE = descriptor.Descriptor(
  name='Subscribe',
  full_name='urpc.pb.Subscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='urpc.pb.Subscribe.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=195,
)


_SERVERLIST_SERVER = descriptor.Descriptor(
  name='Server',
  full_name='urpc.pb.ServerList.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='urpc.pb.ServerList.Server.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='urpc.pb.ServerList.Server.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priority', full_name='urpc.pb.ServerList.Server.priority', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=255,
  serialized_end=309,
)

_SERVERLIST = descriptor.Descriptor(
  name='ServerList',
  full_name='urpc.pb.ServerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='server', full_name='urpc.pb.ServerList.server', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SERVERLIST_SERVER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=197,
  serialized_end=309,
)


_KEYVALUESERIES_KEYVALUE = descriptor.Descriptor(
  name='KeyValue',
  full_name='urpc.pb.KeyValueSeries.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='urpc.pb.KeyValueSeries.KeyValue.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='urpc.pb.KeyValueSeries.KeyValue.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEYVALUESERIES_KEYVALUE_VALUETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=382,
  serialized_end=468,
)

_KEYVALUESERIES = descriptor.Descriptor(
  name='KeyValueSeries',
  full_name='urpc.pb.KeyValueSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='keyValue', full_name='urpc.pb.KeyValueSeries.keyValue', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_KEYVALUESERIES_KEYVALUE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=312,
  serialized_end=468,
)

import Log_pb2

_RESPONSE.fields_by_name['log'].message_type = Log_pb2._LOG
_SERVERLIST_SERVER.containing_type = _SERVERLIST;
_SERVERLIST.fields_by_name['server'].message_type = _SERVERLIST_SERVER
_KEYVALUESERIES_KEYVALUE.containing_type = _KEYVALUESERIES;
_KEYVALUESERIES_KEYVALUE_VALUETYPE.containing_type = _KEYVALUESERIES_KEYVALUE;
_KEYVALUESERIES.fields_by_name['keyValue'].message_type = _KEYVALUESERIES_KEYVALUE

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:urpc.pb.Request)

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:urpc.pb.Response)

class Subscribe(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBSCRIBE
  
  # @@protoc_insertion_point(class_scope:urpc.pb.Subscribe)

class ServerList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Server(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SERVERLIST_SERVER
    
    # @@protoc_insertion_point(class_scope:urpc.pb.ServerList.Server)
  DESCRIPTOR = _SERVERLIST
  
  # @@protoc_insertion_point(class_scope:urpc.pb.ServerList)

class KeyValueSeries(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class KeyValue(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _KEYVALUESERIES_KEYVALUE
    
    # @@protoc_insertion_point(class_scope:urpc.pb.KeyValueSeries.KeyValue)
  DESCRIPTOR = _KEYVALUESERIES
  
  # @@protoc_insertion_point(class_scope:urpc.pb.KeyValueSeries)

# @@protoc_insertion_point(module_scope)
